/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */


plugins {
    id("java")
}

repositories {
    mavenCentral()
}

dependencies {
    compile("io.reactivex:rxjava:1.3.8")
    compile("ch.qos.logback:logback-classic:1.0.13")
    testCompile("junit:junit:4.12")
}
